name: Static Analysis

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Lint and Static Analysis
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 pylint mypy bandit

      - name: Run Flake8
        run: flake8 . --exclude .venv
        continue-on-error: true

      - name: Run Pylint
        run: pylint epic_mixer --exit-zero

      - name: Run Mypy
        run: mypy epic_mixer
        continue-on-error: true

      - name: Run Bandit
        run: bandit -r epic_mixer -q
        continue-on-error: true 